### ISSUE TITLE
Does not support OpenJDK 11

### ISSUE THREAD

**Issue by dkessel** [redtimmy/EnumJavaLibs#1]
What Java version and JRE variant is this supposed to work with?

It does not work with OpenJDK 11 (on Windows 10 64bit).
There is a ClassCastException because OpenJDK seems to use a different ClassLoader class:

```
10:07:55 C:\Users\user\Desktop>java -jar EnumJavaLibs.jar rmi localhost 1099 -d
[*] Fetching jars from C:\Users\user/.serially/jars..
[*] Serializing classes from 1 jars and sending them to RMI endpoint..
Exception in thread "main" java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
        at com.stefanbroeder.serially.EnumJavaLibs.loadJar(EnumJavaLibs.java:264)
        at com.stefanbroeder.serially.EnumJavaLibs.runTest(EnumJavaLibs.java:162)
        at com.stefanbroeder.serially.EnumJavaLibs.<init>(EnumJavaLibs.java:90)
        at com.stefanbroeder.serially.EnumJavaLibs.main(EnumJavaLibs.java:140)
```

**Comment by redtimmy** [comment]
@dkessel [As mentioned in this article](https://www.redtimmy.com/web-application-hacking/remote-java-classpath-enumeration-with-enumjavalibs/), EnumJavaLibs should be used with Java 8

**Comment by dkessel** [comment]
Alright, closing this issue then.
